name: tests

on:
  push:
    branches: ["main"]
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - run: gh auth setup-git
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Hatch & coverage (needed for upload)
      run: |
        python -m pip install --upgrade pip
        pip install coverage hatch
    - name: Run unit tests
      run: hatch run test:run-coverage -- -k unit
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.4.0
      with:
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
